---
# compile openvpn to enable passing username and password from a file

- name: install basic software
  when: ansible_distribution == 'FreeBSD'
  pkgng: name={{ item }}
  with_items:
   - autoconf
   - automake
   - libtool
   - lzo2
   

- name: setting up git source in /usr/src/openvpn
  when: ansible_distribution == 'FreeBSD'
  shell: 'if [ ! -d /usr/src/openvpn ]; then git clone https://github.com/OpenVPN/openvpn.git /usr/src/openvpn ; fi'

  
- name: reset openvpn branch 
  when: ansible_distribution == 'FreeBSD'
  shell: 'if [ -d /usr/src/openvpn ]; then cd /usr/src/openvpn ; git reset --hard ; git checkout release/2.3 ; fi'

- name: reset openvpn branch and update
  when: ansible_distribution == 'FreeBSD'
  shell: 'if [ -d /usr/src/openvpn ]; then cd /usr/src/openvpn ; git reset --hard ; git pull origin ; fi'

  
- name: make configure
  when: ansible_distribution == 'FreeBSD'
  shell: 'if [ -d /usr/src/openvpn ]; then cd /usr/src/openvpn ; autoreconf -i -v -f ; fi'
  
- name: configure openVPN
  when: ansible_distribution == 'FreeBSD'
  shell: 'if [ -d /usr/src/openvpn ]; then cd /usr/src/openvpn ; ./configure  enable_password_save=yes CFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib" ; fi'
 
- name: make and install
  when: ansible_distribution == 'FreeBSD'
  shell: 'if [ -d /usr/src/openvpn ]; then cd /usr/src/openvpn ; make && make install ; fi'
   