---
# common tasks

- name: create common "vpnvm" group
  group: name=vpnvm state=present 
  
- name: add apache user to vpnvm group
  user: name=www-data groups=vpnvm append=yes

- include: debian.yml
  when: ansible_os_family == 'Debian'
  
- include: freebsd.yml
  when: ansible_os_family == 'FreeBSD'

