---
# file for global handelrs - this file is sym linked

- name: restart apache
  service: name=apache2 state=restarted

- name: restart mysqld
  service: name=mysql state=restarted

- name: restart sshd
  service: name=sshd state=restarted 

