---
# file for global handelrs - this file is sym linked

- name: restart apache
  service: name=apache2 state=restarted

- name: restart apache24
  service: name=apache24 state=restarted

- name: restart mysqld
  service: name=mysql state=restarted

- name: restart sshd
  service: name=sshd state=restarted

- name: reboot VM
  shell: "/usr/bin/nohup /bin/sh -c 'sleep 10 ; /sbin/shutdown -r now'  2>&1 /dev/null &"