---

- name: setup PIA-Tunnel on FreeBSD
  hosts: pia-tunnel-freebsd
  remote_user: root
  vars:
    git_branch: "release_php-gui-v2"

  roles:
    - common
    - apache
    - php
    - openvpn
    - pia
