---

- name: setup PIA-Tunnel on a Raspberry running a fresh installation of Raspbian Lite
  hosts: pia-tunnel-raspberry
  remote_user: pi
  sudo: yes
  vars:
    git_branch: "release_php-gui-v2"

  roles:
    - common
    - apache
    - php
    - common
    - openvpn
    - pia
