---
# compile openvpn to enable passing username and password from a file

- name: install basic software
  when: ansible_distribution == 'FreeBSD'
  pkgng: name={{ item }}
  with_items:
   - autoconf
   - automake
   - libtool
   

- name: setting up git source in /usr/src
  when: ansible_distribution == 'FreeBSD'
  shell: ls /usr/src/openvpn &> /dev/null || git clone https://github.com/OpenVPN/openvpn.git /usr/src/openvpn

  
- name: reset openvpn branch 
  when: ansible_distribution == 'FreeBSD'
  shell: ls /usr/src/openvpn &> /dev/null && cd /usr/src/openvpn ; git reset --hard ; git checkout release/2.3

- name: reset openvpn branch and update
  when: ansible_distribution == 'FreeBSD'
  shell: ls /usr/src/openvpn &> /dev/null && cd /usr/src/openvpn ; git reset --hard ; git pull origin

  
- name: make configure
  when: ansible_distribution == 'FreeBSD'
  shell: ls /usr/src/openvpn &> /dev/null && cd /usr/src/openvpn ; autoreconf -i -v -f
  
- name: configure openVPN
  when: ansible_distribution == 'FreeBSD'
  shell: ls /usr/src/openvpn &> /dev/null && cd /usr/src/openvpn ; ./configure --enable-password-save CFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib"
 
- name: make and install
  when: ansible_distribution == 'FreeBSD'
  shell: ls /usr/src/openvpn &> /dev/null && cd /usr/src/openvpn ; make && make install
   