---
# install php56 


- name: install required packages
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - php5
    - php5-curl
    - php5-mcrypt
    - php5-json
  notify: 
    - restart apache
  when: ansible_distribution == 'Debian'