---
# common tasks

- name: set pkg to assume "yes"
  replace: dest=/usr/local/etc/pkg.conf regexp='^#ASSUME_ALWAYS_YES = false;$' replace='ASSUME_ALWAYS_YES = true;'

- pkgng: name="vim" state=present cached="no"
- pkgng: name="openvpn"
- pkgng: name="isc-dhcp43-server"
- pkgng: name="git"
- pkgng: name="ntp"
- pkgng: name="gawk"
- pkgng: name="curl"
- pkgng: name="sudo"
- pkgng: name="bind-tools"
- pkgng: name="zip"
- pkgng: name="dante"
- pkgng: name="3proxy"
- pkgng: name="wget"

- shell: grep -q "supersede domain-name-servers" /etc/dhclient.conf || echo 'supersede domain-name-servers 8.8.8.8, 208.67.222.222, 8.8.4.4, 208.67.220.220;' >> /etc/dhclient.conf

- template: src=dhcpd.conf dest=/usr/local/etc/dhcpd.conf

- shell: grep -q "" /etc/dhclient.conf || echo 'supersede domain-name-servers 8.8.8.8, 208.67.222.222, 8.8.4.4, 208.67.220.220;' >> /etc/dhclient.conf


- shell: "grep -q 'www ALL = NOPASSWD' /usr/local/etc/sudoers || echo 'www ALL = NOPASSWD: /usr/local/pia/*,/usr/local/pia/include/*,/sbin/shutdown' >> /usr/local/etc/sudoers"

- name: install bash
  pkgng: name="bash"

- name: add fstab entries for bash
  shell: "grep -q '/dev/fd' /etc/fstab || echo 'fdesc    /dev/fd    fdescfs    rw    0  0' >> /etc/fstab"

- template: src=pia-autostart.sh dest=/usr/local/etc/rc.d/pia-autostart owner=root group=wheel mode=0555

- shell: grep -q 'vpnvm' /etc/group || pw groupadd vpnvm -M root,www

- shell: pw groupshow vpnvm | grep -q "vpnvm:" && pw groupmod vpnvm -m root,www

- shell: "[ ! -f /bin/bash ] && ln -s /usr/local/bin/bash /bin/bash || exit 0"


